<a href="https://colab.research.google.com/github/binhluong84/Machine-Learning/blob/main/Startup_Funding_Prediction_(Keras_Pipeline)_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Connect Google Drive
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

import tensorflow as tf

from sklearn.metrics import r2_score

In [3]:
data = pd.read_csv('/gdrive/MyDrive/Startup Funding Prediction (Keras Pipeline) tensorflow time preprocessing/startup_funding.csv')

In [4]:
data

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN
...,...,...,...,...,...,...,...,...,...,...
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
 9   Remarks            419 non-null    object
dtypes: int64(1), object(9)
memory usage: 237.9+ KB

In [6]:
def preprocess_inputs(df):
    df = df.copy()
    
    # Drop ID and high-cardinality columns
    df = df.drop(['Sr No', 'Startup Name', 'SubVertical', 'Investors Name'], axis=1)
    
    # Clean \\xc2\\xa0 examples
    df = df.applymap(lambda x: x.replace(r'\\xc2\\xa0', '') if type(x) == str else x)
    
    # Clean target column
    df['Amount in USD'] = df['Amount in USD'].apply(lambda x: x.replace(',', '') if str(x) != 'nan' else x)
    df['Amount in USD'] = df['Amount in USD'].replace({
        'undisclosed': np.NaN,
        'unknown': np.NaN,
        'Undisclosed': np.NaN,
        'N/A': np.NaN,
        '14342000+': '14342000'
    })
    
    # Drop missing target rows
    missing_target_rows = df[df['Amount in USD'].isna()].index
    df = df.drop(missing_target_rows, axis=0).reset_index(drop=True)
    
    # Drop columns with more than 25% missing values
    df = df.drop('Remarks', axis=1)
    
    # Fill categorical missing values with most frequent occurence
    for column in ['Industry Vertical', 'City  Location', 'InvestmentnType']:
        df[column] = df[column].fillna(df[column].mode()[0])
    
    # Clean date column
    df['Date dd/mm/yyyy'] = df['Date dd/mm/yyyy'].replace({
        '05/072018': '05/07/2018',
        '01/07/015': '01/07/2015',
        '22/01//2015': '22/01/2015'
    })
    
    # Extract date features
    df['Date dd/mm/yyyy'] = pd.to_datetime(df['Date dd/mm/yyyy'])
    df['Year'] = df['Date dd/mm/yyyy'].apply(lambda x: x.year)
    df['Month'] = df['Date dd/mm/yyyy'].apply(lambda x: x.month)
    df['Day'] = df['Date dd/mm/yyyy'].apply(lambda x: x.day)
    df = df.drop('Date dd/mm/yyyy', axis=1)
    
    # Convert target column to float
    df['Amount in USD'] = df['Amount in USD'].astype(np.float)
    
    # Split df into X and y
    y = df['Amount in USD']
    X = df.drop('Amount in USD', axis=1)
    
    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, shuffle=True, random_state=1)
    
    return X_train, X_test, y_train, y_test

In [7]:
X_train, X_test, y_train, y_test = preprocess_inputs(data)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:46: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [8]:
X_train

,Industry Vertical,City Location,InvestmentnType,Year,Month,Day
924,eCommerce,Noida,Private Equity,2016,4,10
1108,Consumer Internet,Bangalore,Seed Funding,2016,7,21
1059,Consumer Internet,Mumbai,Private Equity,2016,8,29
160,Consumer Internet,Bengaluru,Seed/ Angel Funding,2018,8,8
1696,on-demand delivery service,Gurgaon,Seed Funding,2015,8,17
...,...,...,...,...,...,...
960,eCommerce,Ahmedabad,Private Equity,2016,10,26
905,Consumer Internet,Mumbai,Private Equity,2016,11,24
1096,eCommerce,New Delhi,Seed Funding,2016,7,15
235,Finance,Chennai,Seed / Angel Funding,2018,2,5
1061,Consumer Internet,Chennai,Private Equity,2016,8,29

In [9]:
y_train

924     4200000.0
1108     595000.0
1059    3000000.0
160     4000000.0
1696     310000.0
          ...
960     1000000.0
905     4000000.0
1096     250000.0
235      450000.0
1061    1000000.0
Name: Amount in USD, Length: 1451, dtype: float64

In [10]:
def build_model():
    inputs = tf.keras.Input(shape=(532,))
    x = tf.keras.layers.Dense(128, activation='relu')(inputs)
    x = tf.keras.layers.Dense(128, activation='relu')(x)
    outputs = tf.keras.layers.Dense(1, activation='linear')(x)
    
    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    
    model.compile(
        optimizer='adam',
        loss='mse'
    )
    
    return model

In [11]:
nominal_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse=False))
])

preprocessor = ColumnTransformer(transformers=[
    ('nominal', nominal_transformer, ['Industry Vertical', 'City  Location', 'InvestmentnType'])
], remainder='passthrough')

regressor = tf.keras.wrappers.scikit_learn.KerasRegressor(build_model)

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('scaler', StandardScaler()),
    ('regressor', regressor)
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: KerasRegressor is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  if __name__ == '__main__':

In [12]:
model.fit(
    X_train,
    y_train,
    regressor__validation_split=0.2,
    regressor__batch_size=32,
    regressor__epochs=100,
    regressor__callbacks=[
        tf.keras.callbacks.EarlyStopping(
            monitor='val_loss',
            patience=3,
            restore_best_weights=True
        )
    ]
)

Epoch 1/100
37/37 [==============================] - 2s 27ms/step - loss: 17648137657122816.0000 - val_loss: 29475037702520832.0000
Epoch 2/100
37/37 [==============================] - 0s 8ms/step - loss: 17648135509639168.0000 - val_loss: 29475035555037184.0000
Epoch 3/100
37/37 [==============================] - 0s 4ms/step - loss: 17648130140930048.0000 - val_loss: 29475029112586240.0000
Epoch 4/100
37/37 [==============================] - 0s 4ms/step - loss: 17648120477253632.0000 - val_loss: 29475018375168000.0000
Epoch 5/100
37/37 [==============================] - 0s 7ms/step - loss: 17648109739835392.0000 - val_loss: 29474992605364224.0000
Epoch 6/100
37/37 [==============================] - 0s 13ms/step - loss: 17648075380097024.0000 - val_loss: 29474949655691264.0000
Epoch 7/100
37/37 [==============================] - 1s 14ms/step - loss: 17648028135456768.0000 - val_loss: 29474889526149120.0000
Epoch 8/100
37/37 [==============================] - 0s 10ms/step - loss: 17647956194754560.0000 - val_loss: 29474795036868608.0000
Epoch 9/100
37/37 [==============================] - 0s 10ms/step - loss: 17647860631732224.0000 - val_loss: 29474676925267968.0000
Epoch 10/100
37/37 [==============================] - 0s 6ms/step - loss: 17647745741357056.0000 - val_loss: 29474530896379904.0000
Epoch 11/100
37/37 [==============================] - 0s 10ms/step - loss: 17647599712468992.0000 - val_loss: 29474350507753472.0000
Epoch 12/100
37/37 [==============================] - 0s 5ms/step - loss: 17647419323842560.0000 - val_loss: 29474140054355968.0000
Epoch 13/100
37/37 [==============================] - 0s 4ms/step - loss: 17647198133026816.0000 - val_loss: 29473878061350912.0000
Epoch 14/100
37/37 [==============================] - 0s 4ms/step - loss: 17646958688600064.0000 - val_loss: 29473564528738304.0000
Epoch 15/100
37/37 [==============================] - 0s 4ms/step - loss: 17646651598438400.0000 - val_loss: 29473238111223808.0000
Epoch 16/100
37/37 [==============================] - 0s 4ms/step - loss: 17646325180923904.0000 - val_loss: 29472827941847040.0000
Epoch 17/100
37/37 [==============================] - 0s 4ms/step - loss: 17645935412641792.0000 - val_loss: 29472396297633792.0000
Epoch 18/100
37/37 [==============================] - 0s 5ms/step - loss: 17645514505846784.0000 - val_loss: 29471917408780288.0000
Epoch 19/100
37/37 [==============================] - 0s 4ms/step - loss: 17645027027058688.0000 - val_loss: 29471402012704768.0000
Epoch 20/100
37/37 [==============================] - 0s 4ms/step - loss: 17644516999692288.0000 - val_loss: 29470759915094016.0000
Epoch 21/100
37/37 [==============================] - 0s 4ms/step - loss: 17644016636002304.0000 - val_loss: 29470244519018496.0000
Epoch 22/100
37/37 [==============================] - 0s 4ms/step - loss: 17643510903603200.0000 - val_loss: 29469699058171904.0000
Epoch 23/100
37/37 [==============================] - 0s 4ms/step - loss: 17642966516498432.0000 - val_loss: 29469078435397632.0000
Epoch 24/100
37/37 [==============================] - 0s 4ms/step - loss: 17642363073593344.0000 - val_loss: 29468397683081216.0000
Epoch 25/100
37/37 [==============================] - 0s 4ms/step - loss: 17641681247535104.0000 - val_loss: 29467641768837120.0000
Epoch 26/100
37/37 [==============================] - 0s 4ms/step - loss: 17640958619287552.0000 - val_loss: 29466860084789248.0000
Epoch 27/100
37/37 [==============================] - 0s 5ms/step - loss: 17640183377690624.0000 - val_loss: 29465983911460864.0000
Epoch 28/100
37/37 [==============================] - 0s 5ms/step - loss: 17639262107205632.0000 - val_loss: 29464946676858880.0000
Epoch 29/100
37/37 [==============================] - 0s 7ms/step - loss: 17638441768452096.0000 - val_loss: 29464044733726720.0000
Epoch 30/100
37/37 [==============================] - 0s 4ms/step - loss: 17637555931447296.0000 - val_loss: 29463149233045504.0000
Epoch 31/100
37/37 [==============================] - 0s 4ms/step - loss: 17636646472122368.0000 - val_loss: 29462174275469312.0000
Epoch 32/100
37/37 [==============================] - 0s 5ms/step - loss: 17635718759186432.0000 - val_loss: 29461016781783040.0000
Epoch 33/100
37/37 [==============================] - 0s 5ms/step - loss: 17634643943620608.0000 - val_loss: 29459859288096768.0000
Epoch 34/100
37/37 [==============================] - 0s 5ms/step - loss: 17633533694574592.0000 - val_loss: 29458620190031872.0000
Epoch 35/100
37/37 [==============================] - 0s 4ms/step - loss: 17632350431084544.0000 - val_loss: 29457344584744960.0000
Epoch 36/100
37/37 [==============================] - 0s 4ms/step - loss: 17631084489474048.0000 - val_loss: 29456002407464960.0000
Epoch 37/100
37/37 [==============================] - 0s 4ms/step - loss: 17629717616132096.0000 - val_loss: 29454342402605056.0000
Epoch 38/100
37/37 [==============================] - 0s 4ms/step - loss: 17628232631189504.0000 - val_loss: 29452798361862144.0000
Epoch 39/100
37/37 [==============================] - 0s 4ms/step - loss: 17626800259596288.0000 - val_loss: 29451058900107264.0000
Epoch 40/100
37/37 [==============================] - 0s 4ms/step - loss: 17625216490405888.0000 - val_loss: 29449437549953024.0000
Epoch 41/100
37/37 [==============================] - 0s 4ms/step - loss: 17623638089924608.0000 - val_loss: 29447584271564800.0000
Epoch 42/100
37/37 [==============================] - 0s 4ms/step - loss: 17621949094035456.0000 - val_loss: 29445705223372800.0000
Epoch 43/100
37/37 [==============================] - 0s 5ms/step - loss: 17620136617836544.0000 - val_loss: 29443909927043072.0000
Epoch 44/100
37/37 [==============================] - 0s 5ms/step - loss: 17618361722601472.0000 - val_loss: 29441706608820224.0000
Epoch 45/100
37/37 [==============================] - 0s 5ms/step - loss: 17616394627579904.0000 - val_loss: 29439541945303040.0000
Epoch 46/100
37/37 [==============================] - 0s 5ms/step - loss: 17614357739339776.0000 - val_loss: 29437478213517312.0000
Epoch 47/100
37/37 [==============================] - 0s 5ms/step - loss: 17612254279106560.0000 - val_loss: 29434961362681856.0000
Epoch 48/100
37/37 [==============================] - 0s 5ms/step - loss: 17610008011210752.0000 - val_loss: 29432526116225024.0000
Epoch 49/100
37/37 [==============================] - 0s 5ms/step - loss: 17607708056223744.0000 - val_loss: 29430215423819776.0000
Epoch 50/100
37/37 [==============================] - 0s 5ms/step - loss: 17605509032968192.0000 - val_loss: 29427501004488704.0000
Epoch 51/100
37/37 [==============================] - 0s 5ms/step - loss: 17603084523929600.0000 - val_loss: 29424939056496640.0000
Epoch 52/100
37/37 [==============================] - 0s 5ms/step - loss: 17600724439400448.0000 - val_loss: 29422192424910848.0000
Epoch 53/100
37/37 [==============================] - 0s 5ms/step - loss: 17598171081342976.0000 - val_loss: 29419551020023808.0000
Epoch 54/100
37/37 [==============================] - 0s 5ms/step - loss: 17595699327664128.0000 - val_loss: 29416608967426048.0000
Epoch 55/100
37/37 [==============================] - 0s 5ms/step - loss: 17592940884918272.0000 - val_loss: 29413812943716352.0000
Epoch 56/100
37/37 [==============================] - 0s 6ms/step - loss: 17590306996224000.0000 - val_loss: 29410832236412928.0000
Epoch 57/100
37/37 [==============================] - 0s 4ms/step - loss: 17587513119997952.0000 - val_loss: 29408042655154176.0000
Epoch 58/100
37/37 [==============================] - 0s 4ms/step - loss: 17584749308542976.0000 - val_loss: 29404735530336256.0000
Epoch 59/100
37/37 [==============================] - 0s 4ms/step - loss: 17581874901680128.0000 - val_loss: 29401557254537216.0000
Epoch 60/100
37/37 [==============================] - 0s 4ms/step - loss: 17578863055863808.0000 - val_loss: 29398368241319936.0000
Epoch 61/100
37/37 [==============================] - 0s 5ms/step - loss: 17575871611142144.0000 - val_loss: 29395089033789440.0000
Epoch 62/100
37/37 [==============================] - 0s 6ms/step - loss: 17572859765325824.0000 - val_loss: 29391552128221184.0000
Epoch 63/100
37/37 [==============================] - 0s 5ms/step - loss: 17569668604624896.0000 - val_loss: 29388180578893824.0000
Epoch 64/100
37/37 [==============================] - 0s 4ms/step - loss: 17566406576963584.0000 - val_loss: 29384349468065792.0000
Epoch 65/100
37/37 [==============================] - 0s 5ms/step - loss: 17562957718224896.0000 - val_loss: 29381042343247872.0000
Epoch 66/100
37/37 [==============================] - 0s 5ms/step - loss: 17559849235644416.0000 - val_loss: 29377254182092800.0000
Epoch 67/100
37/37 [==============================] - 0s 5ms/step - loss: 17556552848244736.0000 - val_loss: 29373790290968576.0000
Epoch 68/100
37/37 [==============================] - 0s 5ms/step - loss: 17553269345746944.0000 - val_loss: 29370287745138688.0000
Epoch 69/100
37/37 [==============================] - 0s 4ms/step - loss: 17549981548281856.0000 - val_loss: 29366566155976704.0000
Epoch 70/100
37/37 [==============================] - 0s 4ms/step - loss: 17546469338775552.0000 - val_loss: 29363076495048704.0000
Epoch 71/100
37/37 [==============================] - 0s 4ms/step - loss: 17543041954873344.0000 - val_loss: 29359135862554624.0000
Epoch 72/100
37/37 [==============================] - 0s 5ms/step - loss: 17539481426984960.0000 - val_loss: 29355201672511488.0000
Epoch 73/100
37/37 [==============================] - 0s 5ms/step - loss: 17535923046580224.0000 - val_loss: 29351087093841920.0000
Epoch 74/100
37/37 [==============================] - 0s 4ms/step - loss: 17532346412564480.0000 - val_loss: 29347024054779904.0000
Epoch 75/100
37/37 [==============================] - 0s 4ms/step - loss: 17528669920559104.0000 - val_loss: 29343081274802176.0000
Epoch 76/100
37/37 [==============================] - 0s 4ms/step - loss: 17525006313455616.0000 - val_loss: 29338998908387328.0000
Epoch 77/100
37/37 [==============================] - 0s 4ms/step - loss: 17521188087529472.0000 - val_loss: 29334813462757376.0000
Epoch 78/100
37/37 [==============================] - 0s 4ms/step - loss: 17517411737534464.0000 - val_loss: 29330634459578368.0000
Epoch 79/100
37/37 [==============================] - 0s 4ms/step - loss: 17513392721887232.0000 - val_loss: 29326723891855360.0000
Epoch 80/100
37/37 [==============================] - 0s 4ms/step - loss: 17509665764016128.0000 - val_loss: 29321962920607744.0000
Epoch 81/100
37/37 [==============================] - 0s 4ms/step - loss: 17505525415542784.0000 - val_loss: 29317633593573376.0000
Epoch 82/100
37/37 [==============================] - 0s 4ms/step - loss: 17501548275826688.0000 - val_loss: 29313265611833344.0000
Epoch 83/100
37/37 [==============================] - 0s 4ms/step - loss: 17497395042451456.0000 - val_loss: 29309239079993344.0000
Epoch 84/100
37/37 [==============================] - 0s 4ms/step - loss: 17493796933599232.0000 - val_loss: 29304239738060800.0000
Epoch 85/100
37/37 [==============================] - 0s 4ms/step - loss: 17489275406778368.0000 - val_loss: 29299903968575488.0000
Epoch 86/100
37/37 [==============================] - 0s 4ms/step - loss: 17485196261588992.0000 - val_loss: 29295389957947392.0000
Epoch 87/100
37/37 [==============================] - 0s 4ms/step - loss: 17481190130843648.0000 - val_loss: 29290613954314240.0000
Epoch 88/100
37/37 [==============================] - 0s 5ms/step - loss: 17476925228318720.0000 - val_loss: 29286127860973568.0000
Epoch 89/100
37/37 [==============================] - 0s 5ms/step - loss: 17472707570434048.0000 - val_loss: 29281637472665600.0000
Epoch 90/100
37/37 [==============================] - 0s 5ms/step - loss: 17468473806422016.0000 - val_loss: 29277022530306048.0000
Epoch 91/100
37/37 [==============================] - 0s 5ms/step - loss: 17464153069322240.0000 - val_loss: 29272824199774208.0000
Epoch 92/100
37/37 [==============================] - 0s 5ms/step - loss: 17460070702907392.0000 - val_loss: 29267706746241024.0000
Epoch 93/100
37/37 [==============================] - 0s 5ms/step - loss: 17455851971280896.0000 - val_loss: 29262711699275776.0000
Epoch 94/100
37/37 [==============================] - 0s 4ms/step - loss: 17451399163936768.0000 - val_loss: 29258259965673472.0000
Epoch 95/100
37/37 [==============================] - 0s 5ms/step - loss: 17447114934059008.0000 - val_loss: 29253456044752896.0000
Epoch 96/100
37/37 [==============================] - 0s 5ms/step - loss: 17442714740064256.0000 - val_loss: 29248701515956224.0000
Epoch 97/100
37/37 [==============================] - 0s 6ms/step - loss: 17438095502737408.0000 - val_loss: 29243843907944448.0000
Epoch 98/100
37/37 [==============================] - 0s 4ms/step - loss: 17433504182697984.0000 - val_loss: 29239196753330176.0000
Epoch 99/100
37/37 [==============================] - 0s 5ms/step - loss: 17429143717150720.0000 - val_loss: 29233572493656064.0000
Epoch 100/100
37/37 [==============================] - 0s 5ms/step - loss: 17424465424023552.0000 - val_loss: 29229268936425472.0000

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('nominal',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse=False))]),
                                                  ['Industry Vertical',
                                                   'City  Location',
                                                   'InvestmentnType'])])),
                ('scaler', StandardScaler()),
                ('regressor',
                 <keras.wrappers.scikit_learn.KerasRegressor object at 0x7f15cfd01a10>)])

In [13]:
y_pred = model.predict(X_test)

rmse = np.sqrt(np.mean((y_test - y_pred)**2))
print("     Test RMSE: {:.2f}".format(rmse))

r2 = r2_score(y_test, y_pred)
print("Test R^2 Score: {:.5f}".format(r2))

20/20 [==============================] - 0s 2ms/step
     Test RMSE: 56371578.25
Test R^2 Score: -0.02111